SCHEDULER_TIMEZONE = 'Europe/Moscow'

PREFERRED_TIME_FORMAT = "%H:%M:%S"
PREFERRED_DATE_FORMAT = "%d.%m.%Y"
PREFERRED_DATETIME_FORMAT = f"{PREFERRED_DATE_FORMAT} {PREFERRED_TIME_FORMAT}"

DAILY_REQUESTS_QUOTA: int = 100
REQUESTS_COUNTER_RESET_TIME: str = "00:00:00"

POINTS_PER_SCORE = 4 # счёт в точности
POINTS_PER_DIFF = 2 # разницу мячей
POINTS_PER_RESULT = 1 # результат
